In [15]:
import pandas as pd
import matplotlib.pyplot as plt
from astroquery.mast import Mast, Observations
from astroquery.ipac.nexsci.nasa_exoplanet_archive import NasaExoplanetArchive
import lightkurve as lk

%matplotlib inline

In [2]:
keb = pd.read_csv(r'../data/kepler-eclipsing-binary-catalog.csv')
keb = keb.drop(columns='Unnamed: 11')
keb.columns

Index(['KIC', 'period', 'period_err', 'bjd0', 'bjd0_err', 'morph', 'GLon',
       'GLat', 'kmag', 'Teff', 'SC'],
      dtype='str')

In [ ]:
keb

,KIC,period,period_err,bjd0,bjd0_err,morph,GLon,GLat,kmag,Teff,SC
0,3863594,0.053268,0.0,55000.000000,0.004327,0.79,-1.0000,-1.0000,-1.000,-1.0,False
1,10417986,0.073731,0.0,55000.027476,0.004231,0.99,81.0390,11.0820,9.128,-1.0,True
2,8912468,0.094838,0.0,54953.576945,0.005326,0.98,80.1095,7.8882,11.751,6194.0,False
3,8758716,0.107205,0.0,54953.672989,0.006197,1.00,77.7478,11.6565,13.531,-1.0,False
4,10855535,0.112782,0.0,54964.629315,0.006374,0.99,79.3949,15.9212,13.870,7555.0,False
...,...,...,...,...,...,...,...,...,...,...,...
2915,9408440,989.985000,-1.0,55346.365980,0.096130,0.00,78.5607,12.2615,13.199,5688.0,False
2916,8054233,1058.000000,-1.0,54751.806288,0.968052,0.03,78.6142,7.7321,11.783,4733.0,False
2917,7672940,1064.270000,-1.0,54977.092960,0.089646,0.00,74.5296,14.6136,12.328,-1.0,False
2918,11961695,1082.815000,-1.0,54871.395674,0.211754,0.02,81.8628,15.9404,13.718,5768.0,False
2919,4360072,1087.300000,-1.0,55165.611684,1.147790,0.05,71.5008,11.7046,11.159,4950.0,False

In [3]:
keb.loc[0]

KIC            3863594
period        0.053268
period_err         0.0
bjd0           55000.0
bjd0_err      0.004327
morph             0.79
GLon              -1.0
GLat              -1.0
kmag              -1.0
Teff              -1.0
SC               False
Name: 0, dtype: object

Sample querying with `MAST` and the `NasaExoplanetArchive` modules

In [ ]:
keplerObs = Observations.query_criteria(target_name='kplr299096355', obs_collection='Kepler')
keplerObs

In [ ]:
tbl = NasaExoplanetArchive.query_criteria(
        table="cumulative", 
        select="*",
        where="kepid = 11446443"
    )

tbl

In [ ]:
NasaExoplanetArchive.query_object("Kepler-16 b")

Looking for common records between MAST and the Villanova Kepler EB Catalog

In [7]:
keb.head()

,KIC,period,period_err,bjd0,bjd0_err,morph,GLon,GLat,kmag,Teff,SC
0,3863594,0.053268,0.0,55000.000000,0.004327,0.79,-1.0000,-1.0000,-1.000,-1.0,False
1,10417986,0.073731,0.0,55000.027476,0.004231,0.99,81.0390,11.0820,9.128,-1.0,True
2,8912468,0.094838,0.0,54953.576945,0.005326,0.98,80.1095,7.8882,11.751,6194.0,False
3,8758716,0.107205,0.0,54953.672989,0.006197,1.00,77.7478,11.6565,13.531,-1.0,False
4,10855535,0.112782,0.0,54964.629315,0.006374,0.99,79.3949,15.9212,13.870,7555.0,False

In [18]:
sampleIndex = 10
sampleKIC = int(keb.loc[sampleIndex]['KIC'])
sampleKIC

7375612

In [19]:
MASTSearch = lk.search_lightcurve(
    f"{sampleKIC}",
    mission="Kepler"
)
MASTSearch

SearchResult containing 19 data products.

 #       mission      year   author   exptime         target_name          distance
                                         s                                  arcsec
--- ----------------- ---- ---------- ------- ---------------------------- --------
  0 Kepler Quarter 00 2009     Kepler    1800                kplr007375612      0.0
  1 Kepler Quarter 01 2009     Kepler    1800                kplr007375612      0.0
  2 Kepler Quarter 02 2009     Kepler    1800                kplr007375612      0.0
  3 Kepler Quarter 03 2009     Kepler    1800                kplr007375612      0.0
  4 Kepler Quarter 04 2010     Kepler    1800                kplr007375612      0.0
  5 Kepler Quarter 05 2010     Kepler    1800                kplr007375612      0.0
  6 Kepler Quarter 06 2010     Kepler    1800                kplr007375612      0.0
  7 Kepler Quarter 07 2010     Kepler    1800                kplr007375612      0.0
  8 Kepler Quarter 08 2011     Kepler    1800                kplr007375612      0.0
  9 Kepler Quarter 09 2011     Kepler    1800                kplr007375612      0.0
 10 Kepler Quarter 10 2011     Kepler    1800                kplr007375612      0.0
 11 Kepler Quarter 11 2012     Kepler    1800                kplr007375612      0.0
 12 Kepler Quarter 12 2012     Kepler    1800                kplr007375612      0.0
 13 Kepler Quarter 13 2012     Kepler    1800                kplr007375612      0.0
 14 Kepler Quarter 14 2012     Kepler    1800                kplr007375612      0.0
 15 Kepler Quarter 15 2013     Kepler    1800                kplr007375612      0.0
 16 Kepler Quarter 17 2013     Kepler    1800                kplr007375612      0.0
 17 Kepler Quarter 16 2013     Kepler    1800                kplr007375612      0.0
 18   Kepler Quarter  2009 KBONUS-BKG    1765 Gaia DR3 2078007608488503680      0.0